In [1]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.6-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/hamzatmuazu/Coursework-Technical-Business-Analyst-Week-1/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/hamzatmuazu/Coursework-Technical-Business-Analyst-Week-1/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
Using cached numpy-2.4.6-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
delinquent_accounts_df = pd.read_csv('delinquent_accounts_export.csv')
finance_assumptions_df = pd.read_csv('finance_assumptions.csv')
recovery_activity_tracker_df = pd.read_csv('recovery_activity_tracker.csv')
smart_recovery_portal_events_df = pd.read_csv('smart_recovery_portal_events.csv')
stakeholder_interview_notes_df = pd.read_csv('stakeholder_interview_notes.csv')

In [10]:
delinquent_accounts_df.head()

,account_id,customer_id,customer_name,product_type,delinquency_stage,days_past_due,overdue_amount,total_balance,risk_flag,current_status,email,mobile_phone,postcode,last_contact_channel,self_service_candidate,created_date
0,ACC-10001,CUST-50001,Naomi Clarke,credit_card,early,28,1747.22,14822.54,N,plan_requested,samuel11@example.net,4.257063e+10,DD6H 8ZY,letter,Y,2025-12-02
1,ACC-10002,CUST-50002,Dr Cameron Osborne,personal_loan,late,71,772.39,11496.59,Y,Awaiting Follow Up,kathleenmann@example.net,2.581352e+10,W3 3NH,email,N,2025-12-09
2,ACC-10003,CUST-50003,Heather Chapman,credit_card,early,26,448.04,14187.91,N,plan_requested,kathleenmorton@example.net,1.390051e+10,CW15 2GJ,phone,Y,2025-11-26
3,ACC-10004,CUST-50004,Rachael Butler-Bryant,credit_card,mid,37,582.96,14010.54,N,email_sent,NaN,4.546383e+10,B5D 7FE,phone,Y,2025-10-06
4,ACC-10005,CUST-50005,William Bryant-Webb,credit_card,mid,45,1300.23,8733.00,N,legal_watch,gerald93@example.org,5.228975e+10,L3 8ZB,email,Y,2025-11-04

In [14]:
#Get all types of current_status
delinquent_accounts_df['current_status'].unique()

<StringArray>
[    'plan_requested', 'Awaiting Follow Up',         'email_sent',
        'legal_watch',    'new_delinquency',        'promise_due',
   'manual_follow_up',  'no_response_cycle', 'awaiting_follow_up',
  'specialist_review',         'email sent',                  nan,
    'new delinquency',   'manual follow up',        'promise due',
     'plan requested', 'awaiting follow up',  'no response cycle',
        'legal watch',  'specialist review']
Length: 20, dtype: str

In [8]:
#total delinquent account count
delinquent_accounts_df.shape[0]

3246

In [9]:
#Total self_service_candiate = Y count
delinquent_accounts_df[delinquent_accounts_df['self_service_candidate'] == 'Y'].shape[0]

2507

In [13]:
#percent of self_service_candidate = Y
percent_self_service_candidate = (delinquent_accounts_df[delinquent_accounts_df['self_service_candidate'] == 'Y'].shape[0] / delinquent_accounts_df.shape[0]) * 100
print(f"Percentage of self_service_candidate = Y: {percent_self_service_candidate:.2f}%")

Percentage of self_service_candidate = Y: 77.23%

In [13]:
finance_assumptions_df.head()

,assumption_id,assumption_name,value,unit,source,confidence_level,notes
0,FA-01,agent_hourly_cost,22.00,GBP,Finance workbook,High,Blended agent hourly cost
1,FA-02,working_days_per_month,21.00,days,Finance workbook,High,Used for admin calculations
2,FA-03,straightforward_case_share,0.38,ratio,Operations estimate,Medium,Suitable for rules-driven self-service
3,FA-04,avg_straightforward_case_minutes,18.00,minutes,Operations leadership,Medium,Current case handling time
4,FA-05,target_straightforward_case_minutes,10.00,minutes,Operations target,Medium,Target after automation support

In [12]:
recovery_activity_tracker_df.head()

,activity_id,account_id,activity_date,activity_type,performed_by,source_system,outcome_code,next_follow_up_date,minutes_spent,duplicate_check_flag
0,ACT-00001,ACC-10001,2026-02-03,status_check,agent_38,spreadsheet,next_action_unclear,NaN,3,N
1,ACT-00002,ACC-10001,19/01/2026,manual_plan_note,agent_48,phone,viewed_status,2026-01-24,8,N
2,ACT-00003,ACC-10001,2026-01-27,status_check,agent_32,phone,promise_to_pay,2026-02-03,4,Y
3,ACT-00004,ACC-10001,2026-02-08,email_sent,agent_08,phone,no_reply,2026-02-13,4,N
4,ACT-00005,ACC-10001,2026-02-06,escalation,agent_28,spreadsheet,next_action_unclear,NaN,8,N

In [7]:
recovery_activity_tracker_df['performed_by'].unique()

<StringArray>
['agent_38', 'agent_48', 'agent_32', 'agent_08', 'agent_28', 'agent_05',
 'agent_04', 'agent_25', 'agent_49', 'agent_09', 'agent_06', 'agent_36',
 'agent_33', 'agent_30', 'agent_27', 'agent_07', 'agent_35', 'agent_34',
 'agent_22', 'agent_01', 'agent_40', 'agent_51', 'agent_53', 'agent_16',
 'agent_43', 'agent_42', 'agent_24', 'agent_50', 'agent_39', 'agent_18',
 'agent_19', 'agent_46', 'agent_21', 'agent_54', 'agent_15', 'agent_29',
 'agent_20', 'agent_44', 'agent_31', 'agent_03', 'agent_56', 'agent_41',
 'agent_23', 'agent_52', 'agent_14', 'agent_47', 'agent_37', 'agent_57',
 'agent_26', 'agent_11', 'agent_58', 'agent_02', 'agent_13', 'agent_10',
 'agent_17', 'agent_55', 'agent_12', 'agent_45']
Length: 58, dtype: str

In [16]:
recovery_activity_tracker_df['source_system'].unique()

<StringArray>
['spreadsheet', 'phone', 'legacy_db', 'email']
Length: 4, dtype: str

In [17]:
recovery_activity_tracker_df['outcome_code'].unique()

<StringArray>
['next_action_unclear',       'viewed_status',      'promise_to_pay',
            'no_reply',     'awaiting_review',         'updated_row',
        'left_message',  'sent_to_specialist']
Length: 8, dtype: str

In [9]:
smart_recovery_portal_events_df.head()

,event_id,journey_id,account_id,event_timestamp,event_step,event_status,selected_action,channel_source,risk_band,eligibility_result
0,EVT-0000001,JRN-000001,ACC-10166,2026-02-27 23:22:00,portal_landing,ok,NaN,email_link,high,ineligible
1,EVT-0000002,JRN-000001,ACC-10166,2026-02-27 23:22:21,identity_verification_started,ok,NaN,email_link,high,ineligible
2,EVT-0000003,JRN-000001,ACC-10166,2026-02-27 23:22:55,identity_verification_passed,ok,NaN,email_link,high,ineligible
3,EVT-0000004,JRN-000001,ACC-10166,2026-02-27 23:23:36,account_summary_viewed,ok,NaN,email_link,high,ineligible
4,EVT-0000005,JRN-000001,ACC-10166,2026-02-27 23:25:13,action_selected,ok,update_details,email_link,high,ineligible